# Generated by Django 3.2.21 on 2024-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_mytests'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='headline',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
